---
name: Device Manager
version: 1.1.2
slug: device_manager
description: A web interface for the device manager
url: https://github.com/TISControlHass/TISDeviceManager
startup: services
boot: auto
ingress: true
ingress_port: 8000
panel_icon: mdi:database
arch:
  - aarch64
  - amd64
  - armv7
init: false
hassio_api: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  upload_limit: int?
ports:
  8000/tcp: 8000
map:
  - data:rw
